// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_mw_test_cpp
NumericVector run_mw_test_cpp(int n_x, int n_y, NumericVector combined, IntegerMatrix synthetic_treatment_idxs);
RcppExport SEXP _lowmoi_run_mw_test_cpp(SEXP n_xSEXP, SEXP n_ySEXP, SEXP combinedSEXP, SEXP synthetic_treatment_idxsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type combined(combinedSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type synthetic_treatment_idxs(synthetic_treatment_idxsSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mw_test_cpp(n_x, n_y, combined, synthetic_treatment_idxs));
    return rcpp_result_gen;
END_RCPP
}
// run_mw_test_cpp_low_level
double run_mw_test_cpp_low_level(int n_x, int n_y, NumericVector combined);
RcppExport SEXP _lowmoi_run_mw_test_cpp_low_level(SEXP n_xSEXP, SEXP n_ySEXP, SEXP combinedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_x(n_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_y(n_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type combined(combinedSEXP);
    rcpp_result_gen = Rcpp::wrap(run_mw_test_cpp_low_level(n_x, n_y, combined));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lowmoi_run_mw_test_cpp", (DL_FUNC) &_lowmoi_run_mw_test_cpp, 4},
    {"_lowmoi_run_mw_test_cpp_low_level", (DL_FUNC) &_lowmoi_run_mw_test_cpp_low_level, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_lowmoi(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
