# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_mw_test_cpp <- function(n_x, n_y, combined, synthetic_treatment_idxs) {
    .Call(`_lowmoi_run_mw_test_cpp`, n_x, n_y, combined, synthetic_treatment_idxs)
}

